version: "3.9"

services:
  web:
    build: .
    container_name: "web"
    env_file:
      - .env
    restart: "always"
    volumes:
      - ./project/local_settings.py:/opt/app/web/project/local_settings.py:ro
      - ./static:/opt/app/web/static
      - ./media:/opt/app/web/media
    depends_on:
      - redis
      - db

  celery:
    build: .
    container_name: "celery"
    command: celery -A proj worker -l info
    env_file:
      - .env
    restart: "always"
    volumes:
      - ./project/local_settings.py:/opt/app/web/project/local_settings.py:ro
      - ./media:/opt/app/web/media
    depends_on:
      - redis
      - db
      - web

  db:
    image: "postgres:14"
    container_name: "db"
    env_file:
      - .env
    restart: "unless-stopped"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:8.0.2-alpine"
    container_name: "redis"
    restart: "always"

  #  nginx:
  #    build:
  #      dockerfile: ./Dockerfile
  #      context: ./nginx/
  #    container_name: "nginx"
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ./static:/opt/app/static
  #      - ./media:/opt/app/media
  #    depends_on:
  #      - web

  caddy:
    image: "caddy:2-alpine"
    container_name: "caddy"
    env_file:
      - .env
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./static:/www/html/static:ro
      - ./media:/www/html/media:ro
    depends_on:
      - web

volumes:
  pgdata:
  static:
  media:
  caddy_data:
  caddy_config:
