version: "3"

services:
  web:
    build: .
    container_name: "web"
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    restart: "always"
    expose:
      - "8000"
    volumes:
      - ./static:/opt/app/static
      - ./media:/opt/app/media
    depends_on:
      - redis
      - db

  db:
    image: "postgres:14"
    container_name: "db"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - ${SQL_PORT}

  redis:
    image: "redis:8.0.2-alpine"
    container_name: "redis"
    restart: "always"
    expose:
      - ${REDIS_PORT}

  nginx:
    image: nginx:1.27
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/opt/app/static
      - ./media:/opt/app/media
    depends_on:
      - web

volumes:
  static:
  media:
  pgdata:
