# Generated by Django 5.2.5 on 2025-08-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='когда обновлен')),
                ('telegram_id', models.CharField(db_index=True, max_length=255, verbose_name='ID в telegram')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='имя пользователя в telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'ordering': ('id',),
            },
        ),
    ]
